ersion: 2.1

jobs:
  preview_deployment:
    docker:
      - image: cimg/node:20.11  
    environment:
      VERCEL_ORG_ID: $VERCEL_ORG_ID
      VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID
    steps:
      - checkout

      # Install project dependencies
      - run:
          name: Install dependencies
          command: npm install

      # Pull Vercel environment settings
      - run:
          name: Pull Vercel Environment Information
          command: npx vercel pull --yes --environment=preview --token=$VERCEL_TOKEN

      # Build the project
      - run:
          name: Build Project Artifacts
          command: npx vercel build --token=$VERCEL_TOKEN

      # Deploy to Vercel
      - run:
          name: Deploy Project Artifacts to Vercel
          command: npx vercel deploy --prebuilt --token=$VERCEL_TOKEN

  production_deployment:
    docker:
      - image: cimg/node:20.11
    environment:
      VERCEL_ORG_ID: $VERCEL_ORG_ID
      VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID
    steps:
      - checkout

      # Install project dependencies
      - run:
          name: Install dependencies
          command: npm install

      # Pull Vercel production settings
      - run:
          name: Pull Vercel Environment Information
          command: npx vercel pull --yes --environment=production --token=$VERCEL_TOKEN

      # Build for production
      - run:
          name: Build Project Artifacts
          command: npx vercel build --prod --token=$VERCEL_TOKEN

      # Deploy production build
      - run:
          name: Deploy Project Artifacts to Vercel
          command: npx vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

workflows:
  version: 2
  preview_and_production:
    jobs:
      - preview_deployment:
          filters:
            branches:
              ignore: /main/
      - production_deployment:
          filters:
            branches:
              only: /main/