version: 2.1
jobs:
  preview_deployment:
    docker:
      - image: cimg/node:20.11.0
    environment:
      VERCEL_ORG_ID: VERCEL_ORG_ID
      VERCEL_PROJECT_ID: VERCEL_PROJECT_ID
      vERCEL_TOKEN: VERCEL_TOKEN
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: sudo npm install --g vercel@latest
      - run:
          name: Pull Vercel Environment Information
          command: vercel pull --yes --environment=preview --token=1WEyRwtwBuihztlJSBKc5Nx5
      - run:
          name: Build Project Artifacts
          command: vercel build --token=1WEyRwtwBuihztlJSBKc5Nx5
      - run:
          name: Deploy Project Artifacts to Vercel
          command: vercel deploy --prebuilt --token=1WEyRwtwBuihztlJSBKc5Nx5

  production_deployment:
    docker:
      - image: cimg/node:20.11.0
    environment:
      VERCEL_ORG_ID: VERCEL_ORG_ID
      VERCEL_PROJECT_ID: VERCEL_PROJECT_ID
      VERCEL_TOKEN: VERCEL_TOKEN
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: sudo npm install -g vercel@latest
      - run:
          name: Pull Vercel Environment Information
          command: vercel pull --yes --environment=production --token=1WEyRwtwBuihztlJSBKc5Nx5
      - run:
          name: Build Project Artifacts
          command: vercel build --prod --token=1WEyRwtwBuihztlJSBKc5Nx5
      - run:
          name: Deploy Project Artifacts to Vercel
          command: vercel deploy --prebuilt --prod --token=1WEyRwtwBuihztlJSBKc5Nx5

workflows:
  version: 2
  preview_and_production:
    jobs:
      - preview_deployment:
          filters:
            branches:
              ignore: /main/
      - production_deployment:
          filters:
            branches:
              only: /main/